### ISSUE TITLE
RUNTIME ERROR Validation error

### ISSUE THREAD

**Issue by TerakoyaAcademia** [heartexlabs/label-studio#1839]
I wanted to do Named Entity Recognition in label studio. For this approach, I have used Label Studio as front end, Redis server as database and Ginza server as ML backed. I have a default Docker file and I have docker-compose.yml file at the bottom.
According to all default setting, I have three containers that are running. (Label studio on port 8080, Ginza Server on 9090 & RedisServer on port 6379). I did health check on Ginza Server and it is showing status UP.
Error Replication:
**Step 1:** Create Project>Labeling Setup > Natural Language Processing > NER and save.
**Step 2:** Click on Setting > Machine Learning > Add Model > (Title: random, Description: random, URL: http://localhost:9090/) > Validate and Save.

1. Dockerfile
```
FROM python:3.8

WORKDIR /tmp
COPY requirements.txt .

RUN pip install --no-cache \
                -r requirements.txt \
                uwsgi==2.0.19.1 \
                supervisor==4.2.2 \
                click==7.1.2 \
                label-studio==1.4 \
                ginza==5.0.3 \
                ja-ginza-electra==5.0.0 \
                git+https://github.com/heartexlabs/label-studio-ml-backend
RUN pip install label-studio-ml

COPY uwsgi.ini /etc/uwsgi/
COPY supervisord.conf /etc/supervisor/conf.d/

WORKDIR /app

COPY *.py /app/

EXPOSE 9090

CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
```
2. docker-compose.yml 
```
version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
    
  server:
    container_name: ginza_server
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./data/server:/data"
      - "./logs:/tmp"
      - "./output:/app/output"
    
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - 8080:8080
    volumes: 
      - "./mydata:/label-studio/data"
```
After clicking on Save button, the following error is shown.
![errorDisplay](https://user-images.githubusercontent.com/85092129/145791433-298192a5-516d-4eef-9050-a26fad3deed1.png)

Health Check status manually on port 9090:
![3  healthCheck](https://user-images.githubusercontent.com/85092129/145791962-c7aab202-5038-42c1-9a30-bc9162f90aea.png)

Console Error: 
![consoleDispaly](https://user-images.githubusercontent.com/85092129/145791482-5a0fde58-6016-4bec-8a7a-e5ac551d1059.png)
