### ISSUE TITLE
Can't change host and port 

### ISSUE THREAD

**Issue by master1c** [heartexlabs/label-studio#3388]
**Describe the bug**
Can not use another port and a subdomain with label-studio. if I do not specify the port and/or the subdomain label-studio works as expected. 

Label Studio version: 1.6.0
**To Reproduce**
Go to console: 
type `label-studio start --host=http://localhost:18081/labelstudio`

**Expected behavior**
label-studio opens in the browser
instead it starts the server and opens the browser with ERR_EMPTY_RESPONSE

**Screenshots**
![image](https://user-images.githubusercontent.com/115220299/206263282-d26f3be5-160a-4c0b-b5f8-3208cef1232e.png)

**Environment (please complete the following information):**
 - OS: Windows 10 
 - Label Studio Version 1.6.0

**Additional context**
Didn't work with linux as well.

**Comment by alfmagar** [comment]
I'm having this exact issue.

Have an Nginx reverse proxy docker container with other services (MLFlow, Airflow, Prometheus, Grafana...) and want to add Label Studio as a subfolder for the current config.

https://server/grafana or https://server/airflow works like a charm for example.

Tried multiple configurations with Label Studio HOST and LABEL_STUDIO_HOST environment variables, but i'm still getting that error.

**Comment by makseq** [comment]
@alfmagar @master1c this feature will work only if you are using our nginx + docker compose configuration.

**Comment by field210** [comment]
@makseq could you please provide more details about how to setup using "your nginx + docker compose configuration."?

**Comment by farioas** [comment]
@field210 https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-with-a-host-and-sub-path

**Comment by BnJam** [comment]
Hi, 

I didn't use the Helm install for LS on AKS but rather a Deployment+Service manifest behind  an NGINX Ingress Controller through an OAuth2-Proxy redirect for authentication to the main LS page. I didn't look at SSO or the like after OAuth2-Proxy because I got what I needed working. 

I understand the awkwardness of double authentication but I needed a way to manage User access outside of LS - which ended up being a GitHub Team and that is why I used OAuth2-Proxy. 

This is how I set up LS on a subpath to my host:

Service

<details>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: label-studio
  namespace: labelstudio
spec:
  selector:
    app: label-studio
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: label-studio
```

</details>

Deployment

<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
  namespace: labelstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      initContainers:
      - name: volume-mount-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1001:1001 /label-studio/data"]
        securityContext:
          privileged: true # not ideal /fix
        volumeMounts:
        - name: label-studio
          mountPath: /label-studio/data
      containers:
        - name: label-studio
          image: <acr-domain>/<artifact-path>/label-studio:1.8.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: label-studio
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            privileged: true # not ideal /fix
          env:
            - name: LABEL_STUDIO_HOST
              value: https://<hostname>/label-studio
            - name: LABEL_STUDIO_SERVICE_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: label-studio
              mountPath: /label-studio/data
              mountPropagation: Bidirectional
      volumes:
        - name: label-studio
          persistentVolumeClaim:
            claimName: label-studio-pvc
```

</details>

PVC

<details>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: label-studio-pvc
  namespace: labelstudio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  storageClassName: managed-csi
```

</details>

and Ingress

<details>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ls-ingress
  namespace: labelstudio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-type
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # annotation for oauth2-proxy callbacks
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://<proxy-host>/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://<proxy-host>/oauth2/start?rd=https://$host$request_uri$is_args$args"
    # subpath rewrite without changing the Docker Image
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    
spec:
  ingressClassName: my-ingress-cls
  rules:
    - host: <hostname>
      http:
        paths:
          - path: /label-studio/?(.*)
            pathType: ImplementationSpecific
            backend:  
              service:
                name: label-studio
                port:
                  number: 80
   tls:
    - hosts:
        - <hostname>
      secretName: <secret-name>-tls
```

</details>

hope this is helpful for your documentation! 

SSO would be an excellent attribute for the community outside of the Enterprise Edition.
