### ISSUE TITLE
Hide "Auto accept annotation suggestions" message

### ISSUE THREAD

**Issue by 35grain** [heartexlabs/label-studio#3503]
**Is your feature request related to a problem? Please describe.**
Is there a way to hide the "Auto accept annotation suggestions" message when labelling tasks?
![pilt](https://user-images.githubusercontent.com/7030797/210066967-5da438ac-f093-4a05-8cc6-b391cf585348.png)

**Describe the solution you'd like**
A setting to hide the "Auto accept annotation suggestions" message as it can obstruct some labelled objects,

**Describe alternatives you've considered**
Tried messing around with the settings, couldn't find anything useful.

**Comment by makseq** [comment]
@35grain Probably you added ML models and turned on `Use for interactive preannotations` ON. Try to disable it. 

![image](https://user-images.githubusercontent.com/501780/211030498-74afc904-8058-42f7-97a3-f41179154751.png)

**Comment by 35grain** [comment]
Indeed, enabling interactive preannotations is what makes the checkbox appear - but what if I want to get rid of this obstructive message **while keeping the preannotations enabled**? I think the solution would be to have the checkbox appear elsewhere.

**Comment by makseq** [comment]
Are you sure you need **interactive** preannotations? Because if you need them, you need this flag with message and it should help you in your work.

**Comment by Avi197** [comment]
I think it's more obscure than helping in my work. The message box cover the top of the image that make labeling the top area rather hard and annoying

**Comment by duxan** [comment]
I also need interactive preannotations and this option is obstructing the view - part of the image cannot be labelled.

**Comment by skanelo** [comment]
I need this as well 😕 and I was looking at how I could hide this option while using the interactive preannotation feature. I found this thread [issue #4103](https://github.com/heartexlabs/label-studio/issues/4103) in which it is suggested to *add "position:relative" in the main.css file*. I tried to modify a couple of lines from **"position:absolute"** to **"position:relative"** in this file, and restarted the server but didn't work. Not sure how I can hide this tab on the top of the window. Any ideas?

**Comment by duxan** [comment]
File needing a change is this one: `label_studio/frontend/dist/lsf/css/main.css`

If you're running the studio from docker image as part of docker compose, I used this to change the line and still set appropriate entrypoint:

```
services:
  studio:
    image: "heartexlabs/label-studio:latest"
    container_name: studio
    ports:
      - "8080:8080"
    volumes:
      - "./data/studio:/label-studio/data"
    command: >
      bash -c "sed -i 's/\.lsf-dynamic-preannotations-control{/\.lsf-dynamic-preannotations-control{position:relative !important;/g' label_studio/frontend/dist/lsf/css/main.css &&
      ./deploy/docker-entrypoint.sh &&
      label-studio"
```
