### ISSUE TITLE
When trying to run the docker container I get: "PermissionError: [Errno 13] Permission denied: '/label-studio/data/media'"

### ISSUE THREAD

**Issue by BikiniBottomsVeryOwn** [heartexlabs/label-studio#3766]
First I ran: 
`docker pull heartexlabs/label-studio:latest`
That went fine.

Then,
When I run the command: 
`docker run -it -p 8080:8080 -v $(pwd)/mydata:/label-studio/data heartexlabs/label-studio:latest`

I get the response: "PermissionError: [Errno 13] Permission denied: '/label-studio/data/media"

Windows 11 WSL 2 default Ubuntu shell. Docker desktop installed running via wsl2.

**Comment by nikitabelonogov** [comment]
Hi @BikiniBottomsVeryOwn 

Most likely this is related to non-root user 
Try running `chown` as it suggested in release notes 
https://github.com/heartexlabs/label-studio/releases/tag/1.7.0
> Breaking changes
Starting with this release, the application will run using a non-root docker user with ID 1001.

> If you encounter any permission issues when running the application in a docker container, you can fix them by changing the ownership of the relevant files and directories to 1001.

> ```docker run -it --user root -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:1.7.0 chown -R 1001:root /label-studio/data/```

**Comment by WillieMaddox** [comment]
If using docker_compose, what would we need to change in the `docker_compose.yml`?

**Comment by farioas** [comment]
No changes required, just run the command from the message above

**Comment by WillieMaddox** [comment]
For docker_compose, I don't run the above command, I simply run,
```sh
$ docker-compose up
```
All the details are kept in the docker_compose.yml.  That's why I was asking.

**Comment by tridivbwise** [comment]
I have the same issue with `docker compose up`. The error message can be found below,

![image](https://user-images.githubusercontent.com/124601360/226908654-d0e8c7a3-384a-473d-a773-c270a1abe91a.png)

After this when I try to access the http://localhost:8080/, I get the following screen which I assume is because of the issue with file ownership. I tried the changes suggested by Gornoka, but that didn't work either.

![image](https://user-images.githubusercontent.com/124601360/226909091-a236dc1c-cb76-4e65-ad43-3df44939010d.png)

**Comment by tridivbwise** [comment]
As a workaround till the issue is fixed, to get it to work with docker compose, first run `docker compose up` and let it pull all the images. The base image will be named heartexlabs/label-studio:latest. This is slightly different from the fix mentioned in the release notes as the image tag over there is 1.7.0. Just stop the docker containers with `docker compose down` and then run the following command to fix the problem. After this, the containers should start without the `permission denied ` error.

```
docker run -it --user root -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest chown -R 1001:root /label-studio/data/
```

**Comment by TrueWodzu** [comment]
I guess docker_compose.yml or other parts of configuration should be changed so it would not start with this error.

**Comment by WillieMaddox** [comment]
In all the posts I've seen, the `chown -R 1001:root` is being run on the container volume path, not the host volume path.   To get this working, I had to `chown -R 1001:root` the host half of `/my/local-storage/data:/label-studio/data:rw`, as well as any `Target Cloud Storage` defined for projects.   Irritating...

**Comment by farioas** [comment]
Kindly read this article: https://labelstud.io/guide/install.html#PermissionError-Errno-13-Permission-denied-label-studio-data-media

**Comment by Parth971** [comment]
I have used this docker information inside yml file as below, It worked
```version: "3.8"

services:
    label_studio:
        image: heartexlabs/label-studio:latest
        container_name: label_studio
        ports:
            - 8508:8080
        volumes:
            - ./mydata:/label-studio/data
        env_file:
            - .env
        depends_on:
            - postgres_db
        environment:
            - DJANGO_DB=default
            - POSTGRE_NAME=ls
            - POSTGRE_USER=postgres
            - POSTGRE_PASSWORD=postgres
            - POSTGRE_PORT=5432
            - POSTGRE_HOST=postgres_db
        command: sh -c "chown -R 1001:root /label-studio/data && label-studio start"

    postgres_db:
        image: postgres:latest
        container_name: db
        ports:
            - 5433:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ls

volumes:
    mydata:
    postgres-data:
```

**Comment by frippe75** [comment]
Well using podman on Fedora I cannot get this to work either. After failing getting Label Studio working on GKE ... My thinking is getting 1,2 and 3 working before going feature-rich.

**Comment by victorconka** [comment]
[This](https://github.com/HumanSignal/label-studio/issues/3465#issuecomment-1365707616) solution worked for me.

**Comment by Maksim-Goncharovskiy** [comment]
> If using docker_compose, what would we need to change in the `docker_compose.yml`?

I decided to add one more service in docker-compose.yaml:
```yaml
fix-data-permissions:
    image: heartexlabs/label-studio:latest
    user: root
    volumes:
      - ./mydata:/label-studio/data
    command: chown -R 1001:root /label-studio/data
    restart: "no"
```
Also don't forget to add dependency on this service for the app:
```yaml
app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
      - fix-data-permissions  # this is new one
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
    #      - LOG_LEVEL=DEBUG
    volumes:
      - ./mydata:/label-studio/data:rw
    command: label-studio-uwsgi
```

It worked for me.
