### ISSUE TITLE
Docker Compose: Nginx Configuration Issue

### ISSUE THREAD

**Issue by mikeaadd** [heartexlabs/label-studio#4286]
**Describe the bug**
Using custom nginx configuration file does not override default configuration if done according to comments in docker compose file

**To Reproduce**
In your docker compose file if you would like to override the default nginx conf file, your nginx configuration should look something like this...

```
  nginx:
    build: .
    image: heartexlabs/label-studio:latest
    ports:
      - "80:8085"
      - "8081:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
#   Optional: Specify SSL termination certificate & key
#   Just drop your cert.pem and cert.key into folder 'deploy/nginx/certs'
#      - NGINX_SSL_CERT=/certs/cert.pem
#      - NGINX_SSL_CERT_KEY=/certs/cert.key
    volumes:
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/certs:/certs:ro
#   Optional: Override nginx default conf
      - ./deploy/nginx/default.conf:/label-studio/deploy/nginx/default.conf
```

**Expected behavior**

The comment implies that this should override nginx configuration but it doesn't.  

**Additional context**
After some debugging I found that changing the destination configuration location to `/etc/nginx/nginx.conf` works. 
The suggestion here is to update the line to 
`
      # - ./deploy/nginx/default.conf:/etc/nginx/nginx.conf
`
Happy to create a PR if you guys would like.
