### ISSUE TITLE
URLs With “Next” Parameter Use Base URL Instead of Sub Path

### ISSUE THREAD

**Issue by PaulP49** [heartexlabs/label-studio#4520]
**Describe the bug**
When running label-studio on a sub path, the URLs with "next" parameter use the base URL instead of the full URL including the sub path.

**To Reproduce**
1. Create a `docker-compose.yml` file with content:
```yaml
version: "3.9"
services:
  nginx:
    image: dockerregistry-v2.vih.infineon.com/heartexlabs/label-studio:1.8.0
    ports:
      - "8085:8085"
      - "8086:8086"
    command: nginx
    environment:
      - LABEL_STUDIO_HOST=http://localhost:8085/label-studio

  app:
    image: dockerregistry-v2.vih.infineon.com/heartexlabs/label-studio:1.8.0
    expose:
      - "8000"
    command: label-studio-uwsgi
    environment:
      - LABEL_STUDIO_HOST=http://localhost:8085/label-studio
```
2. Run `docker compose up`
3. Navigate to `http://localhost:8085/label-studio/projects/` in the browser while not logged in
4. You get redirected to `http://localhost:8085/?next=/label-studio/projects/`, which shows an nginx 404 not found error.

**Expected behavior**
1. Navigate to `http://localhost:8085/label-studio/projects/` in the browser while not logged in
2. Redirect goes to `http://localhost:8085/label-studio/?next=/projects/`

**Screenshots**
![image](https://github.com/heartexlabs/label-studio/assets/39067132/d0fd93de-9b5e-4ad8-ac10-f347ce07dd50)

**Environment (please complete the following information):**
 - OS: Ubuntu (WSL)
 - Label Studio Version: 1.8.0
