### ISSUE TITLE
Cannot connect to customize ML backend(sometimes) but all thing seems ok

### ISSUE THREAD

**Issue by DeathKing** [heartexlabs/label-studio#4642]
**Describe the bug**

1. I have deployed LS, LS-ml and minio storage in a single docker-compose file with same network(listed in [1]):
2. With all things are well configured(including labeling configuration), then I goto **Setting** -> **Machine Learning**, the default model I specified in command line turned out **'Error'**, but I am sure that sometimes it is ok.
3. I clicked 'Edit' to modified the model backend, but didn't pass the verification

![not_passing_validation](https://github.com/HumanSignal/label-studio/assets/895809/4dcf39ee-cdea-46e7-8071-21b0c9607163)

4. I made following checks:
  - network connection form LS to LS-ml-backend, seems ok:
![curl_from_ls](https://github.com/HumanSignal/label-studio/assets/895809/05e06c77-ff17-482d-aab3-9e9b30e76d0c)
  - LS-ml-backend log checking, seems ok:
![modeling_container_seems_ok](https://github.com/HumanSignal/label-studio/assets/895809/aae8374e-9abe-405b-87f1-1a7965b4a49e)
  - checking `logs/uwsgi.log`, not found.
![no_log](https://github.com/HumanSignal/label-studio/assets/895809/3506df58-ad93-4849-a6b6-91ee07b9acd8)

Is there any clue?

**To Reproduce**
see [Describe the bug]

**Expected behavior**
1. backend was correctly setup.
2. (or) information with stacktrace was provided to debug the error.

**Screenshots**
see [Describe the bug]

**Environment (please complete the following information):**
 - OS: MacOS 13.4 (22F66)
 - Label Studio Version: docker heartexlabs/label-studio:1.8.1
 - label-studio-ml: 1.0.9
 - Werkzeug: 2.0.2
 - docker version:
   - docker Desktop 4.22.0 (117440)
   - Engine: 24.0.5
   - Compose: v2.20.2-desktop.1

**Additional context**

1. used docker-compose.yaml
```yaml
version: "3.2"

services:
  labeling:
    container_name: labeling_container
    image: heartexlabs/label-studio:1.8.1
    ports: 
      - 8080:8080
    depends_on:
      - modeling
    volumes: 
      - ${DATA:-./data}:/label-studio/data
      - ./labeled:/label-studio/labeled
      - ./labeling/configs:/label-studio/configs
    command: > 
      bash -c "
      label-studio init /labeled
      --username admin@localhost
      --password admin
      --label-config=configs/${CONFIG:-labeling-config.xml} 
      --port 8080 
      --ml-backends http://modeling_container:9090 &&
      label-studio start /labeled
      --host labeling_container:8080
      --port 8080 
      --log-level DEBUG"
    restart: always
  modeling:
    container_name: modeling_container
    build: 
      context: ./modeling
    ports: 
      - 9090:9090
    environment:
      - ACCESS_KEY=some-access-key
      - SECRET_KEY=some-secret-key
    volumes:
      - ./modeling/tools:/annotation_service_modeling/tools
    command: >
      bash -c "
      label-studio-ml init modeling_backend 
      --script tools/${MODEL:-model.py}
      --force &&
      label-studio-ml start modeling_backend 
      --debug
      --port 9090"
    restart: always

  storage:
    image: quay.io/minio/minio:RELEASE.2023-08-09T23-30-22Z
    container_name: storage_container
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./storage/data1:/data1"
    command: server --console-address ":9001" /data1
    environment:
      - MINIO_ROOT_USER=******
      - MINIO_ROOT_PASSWORD=******
      - MINIO_ACCESS_KEY=******
      - MINIO_SECRET_KEY=******
```
