### ISSUE TITLE
Importing Data from URL results in "Validation error(undefined)" 

### ISSUE THREAD

**Issue by Nana2929** [heartexlabs/label-studio#4954]
**Describe the bug**
Cannot connect to the local storage. 
A very similar issue: https://github.com/HumanSignal/label-studio/issues/3521 (but unanswered) 
**To Reproduce**
1. `docker compose up` with the below `docker-compose.yaml`. 
```yaml
version: "3.9"
services:
  label-studio:
    user: "root"
    image: heartexlabs/label-studio:latest
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/nanaeilish/projects
    container_name: label-studio-ofa
    restart: unless-stopped
    ports:
      - "8081:8080" #external:internal
    volumes:
      - ./docker_volumes:/label-studio/data:rw
```
2. Go to the GUI from the link `http://0.0.0.0:8081/projects/1/settings/storage` (I do not use 8080 port because it is already in use). 
3. Add a source storage from local files. I have verified that the path exists. 
```
❯ pwd
/home/nanaeilish/projects/recommender/Gest
```
4. Validation Error. 

**Expected behavior**
Connection Success. 
**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/58811089/0d56b731-a2d9-4f3d-a7ba-d68063ae686e)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Label Studio Version:1.8.0

**Additional context**
- I tried to follow the [video](https://www.youtube.com/watch?v=lo6ncQajbdU) but no luck. 
- I have checked that the files are on the same device as I started the label studio docker container. 
- Although seemingly unrelated I'd like to mention that the image folder `/home/nanaeilish/projects/recommender/Gest`  is laid out like a prefix tree structure, part of the folder `tree` view: 
```
│       │   ├── T1
│       │   │   ├── 4V
│       │   │   │   └── AF1QipM_T14V8vm9EgEsn1OU_SYFmQ_8cqeaLsjyThDW.jpg
│       │   │   ├── Gz
│       │   │   │   └── AF1QipM_T1GzYOm4lUDEy8LgNssafpk6UdIoY0Ik1wr4.jpg
│       │   │   ├── RY
│       │   │   │   └── AF1QipM_T1RYBfgGcTkmm41OEmkU3oRu2qq2wcCQY2GK.jpg
│       │   │   └── Xc
│       │   │       └── AF1QipM_T1Xc0ZYKcUWjutn0pz8433zWsMEKq6-Ch61-.jpg
```
