### ISSUE TITLE
The label images cannot be displayed on Web

### ISSUE THREAD

**Issue by zhangyhdgut** [heartexlabs/label-studio#5200]
**Describe the bug**
I use the MinIO as the Label Studio Data Storage, and the label images were successfully uploaded using Minio, but they cannot be displayed on the page.

In Label Studio Project Web Page, I found the 'image' filed in task is erro.

![image](https://github.com/HumanSignal/label-studio/assets/152574205/c09743dd-d622-4f4a-869f-c5fdfc3e7cd1)

The MinIO Console information:
![image](https://github.com/HumanSignal/label-studio/assets/152574205/8f275b48-892d-4be4-94fb-27edffb56576)

**To Reproduce**
The 'docker-compose.yml':
``` yaml
  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
      - LOG_LEVEL=DEBUG
      - MINIO_STORAGE_ACCESS_KEY=${MINIO_ROOT_USER:-minio_admin_do_not_use_in_production}
      - MINIO_STORAGE_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minio_admin_do_not_use_in_production}
      - MINIO_STORAGE_BUCKET_NAME=data
      - MINIO_STORAGE_ENDPOINT=http://minio:9000
    volumes:
      - /home/zhouli/docker/labeling_192/mydata:/label-studio/data:rw
    command: label-studio-uwsgi
```

**Expected behavior**
Successfully displayed on the page.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - label studio tag 1.9.2
