### ISSUE TITLE
Serving an Image File from a Static Server Gives "There was an issue loading URL from $image value" error

### ISSUE THREAD

**Issue by wpm** [heartexlabs/label-studio#5252]
**Describe the bug**
I am trying to create a bounding box image annotation project where the images are served from a static file server. The image file is served, but I get a "There was an issue loading URL from $image value" error in Label Studio. It looks like this.

<img width="1293" alt="label-studio-error" src="https://github.com/HumanSignal/label-studio/assets/141456/969eb87c-e0cc-4aa2-8ad1-40e0509fd5bc">

I can't get Label Studio to do the labeling task.

**To Reproduce**
1. Install Label Studio and a static file server using the following `docker-compose.yml` file.
```yaml
version: "3.8"

services:
  label-studio:
    container_name: label-studio
    image: heartexlabs/label-studio:latest
    ports:
      - "8080:8080"
    volumes:
      - label-studio:/label-studio/data

  image-server:
    container_name: image-server
    image: joseluisq/static-web-server:2.24.0-alpine
    environment:
      - SERVER_CORS_ALLOW_ORIGINS=*
      - SERVER_DIRECTORY_LISTING=true
      - SERVER_DIRECTORY_LISTING_ORDER=0
      - SERVER_HEALTH=true
    ports:
      - "8787:80"
    volumes:
      - image-server:/public

volumes:
  image-server:
  label-studio:
```
2. Run `docker compose up`.
3. Copy an image file called `my-image.png` to the `/public` directory on the image server, the root of its file share.
4. Verify that the image file is visible at http://localhost:8787/my-image.png.
5. Create a Label Studio project with a labeling configuration identical to the [example bounding box labeling configuration](https://labelstud.io/templates/image_bbox#Labeling-Configuration) in the Label Studio documentation.
```html
<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue"/>
  </RectangleLabels>
</View>
```
7. Import project data by uploading a CSV file that has the following contents:
```csv
image
http://localhost:8787/my-image.png
```
8. When you try to label the task you see the error.

Because the error message mentions CORS I tried

1. Removing the `SERVER_CORS_ALLOW_ORIGINS` environment variable on the static server.
2. Setting the the `SERVER_CORS_ALLOW_ORIGINS` environment variable in the static server to `http://localhost:8787`.

In both these cases I saw the same error as before.

**Expected behavior**
I expect the image to be displayed in the Labeling UI.

**Environment:**
 - OS: Mac OS 14.2.1
 - Label Studio Version 1.10.0
