### ISSUE TITLE
Prediction score min option does not exists.

### ISSUE THREAD

**Issue by reinoldus** [heartexlabs/label-studio#532]
**Describe the bug**
Prediction score min option does not exists.

`label-studio start-multi-session: error: argument --sampling: invalid choice: 'prediction-score-min' (choose from 'sequential', 'uniform')`

**To Reproduce**

1. Use this docker-compose:
```
version: '3'

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    volumes:
      - /root/session_projects:/label-studio/session_projects
    command: "label-studio start-multi-session --use-gevent --root-dir /label-studio/session_projects --sampling=prediction-score-min"
    restart: unless-stopped
```
2. 

**Expected behavior**
According to the doc it should be possible to add sampling via the cmd: https://labelstud.io/guide/tasks.html#Sampling

**Screenshots**

**Environment (please complete the following information):**
 - OS: docker image
 - Label Studio Version: latest docker image
