### ISSUE TITLE
Error rendering custom app.labels in helm chart

### ISSUE THREAD

**Issue by mmx86** [heartexlabs/label-studio#5616]
**Describe the bug**
Incorrect nindent here https://github.com/HumanSignal/charts/blob/master/heartex/label-studio/templates/app-deployment.yaml#L8 results in incorrect labels render.

**To Reproduce**
***values.yaml***
```yaml
app:
  labels:
    custom: "value"
```
```helm template label-studio --values values.yaml --debug```
renders incorrect labels:
```yaml
---
# Source: label-studio/templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-ls-app
  labels:
    helm.sh/chart: label-studio-1.4.0
    app.kubernetes.io/name: ls-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.11.0"
    app.kubernetes.io/managed-by: Helm
        custom: value
spec:
  replicas: 1
...
```
