### ISSUE TITLE
Import data - "key.json" not found

### ISSUE THREAD

**Issue by avanmalleghem** [heartexlabs/label-studio#6077]
**Describe the bug**
I deployed label studio locally using docker compose (found here https://github.com/HumanSignal/label-studio/blob/develop/docker-compose.yml). I added several environment variables to the app container (in docker-compose.yml file) : 
```
  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      [...]
      - STORAGE_TYPE=gcs
      - STORAGE_GCS_BUCKET_NAME="test-bucket-antoine"
      - STORAGE_GCS_PROJECT_ID="otto-ai-dev-519a"
      - STORAGE_GCS_FOLDER=""
      - GOOGLE_APPLICATION_CREDENTIALS="/opt/heartex/secrets/key.json"
    volumes:
      - ./mydata:/label-studio/data:rw
      - ./service-accounts.json:/opt/heartex/secrets/key.json:ro
    command: label-studio-uwsgi
```

Unfortunately, when I try to import data in the UI, I receive the following error : 
![image](https://github.com/HumanSignal/label-studio/assets/7413624/d6dad7a0-2941-4c96-8790-82e3f0cd2abd)

I verified in the docker container directly and the file is there (I used `docker exec -it labelstudio-app-1 bash` to enter the container): 
![image](https://github.com/HumanSignal/label-studio/assets/7413624/2c07c842-73b0-4d68-9323-30b26fca846d)

**To Reproduce**
1. Add environment variables and volume shown above to the default docker-compose file found https://github.com/HumanSignal/label-studio/blob/develop/docker-compose.yml
2. docker compose up
3. Create a user then a project
4. Try to import a file and see the error.

**Expected behavior**
The file should be uploaded to the GCS

**Environment (please complete the following information):**
 - OS: Ubuntu 22
 - Label Studio Version 1.12.1
