### ISSUE TITLE
A bug with CSRF  after update label-studio

### ISSUE THREAD

**Issue by lgq-garbage** [heartexlabs/label-studio#6296]
![17253509171808](https://github.com/user-attachments/assets/3351cb23-7767-47b9-b600-c7bece2fcf3d)

I update label-studio to the newest version and run  docker-compose up -d --build.    

But when I open the 8080 port, the website shows these.(Include edge or chrome

**Comment by lgq-garbage** [comment]
This problem appears again. Anyone meets this problem？  I don’t know how to adjust files.

**Comment by june-oh** [comment]
Same problem

**Comment by june-oh** [comment]
I found a temporary workaround. Add `USE_ENFORCE_CSRF_CHECKS=false` to the `docker-compose.yml` file as shown below:
```
app:  
   stdin_open: true  
   tty: true  
   build: .  
   image: heartexlabs/label-studio:latest  
   restart: unless-stopped  
   expose:  
     - "8000"  
   depends_on:  
     - db  
   environment:  
     - DJANGO_DB=default  
     - POSTGRE_NAME=postgres  
     - POSTGRE_USER=postgres  
     - POSTGRE_PASSWORD=  
     - POSTGRE_PORT=5432  
     - POSTGRE_HOST=db  
     - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}  
     - JSON_LOG=1  
     - USE_ENFORCE_CSRF_CHECKS=false     #add this line 
```
