### ISSUE TITLE
Accessing S3 files in labeling tasks yields network error

### ISSUE THREAD

**Issue by DrissiReda** [heartexlabs/label-studio#6495]
Hello, I have created a Project for labeling data, my task json file contains an s3 url, I expect the UI to download that file and display it for the annotator to start annotating. However I'm getting this error:

![image](https://github.com/user-attachments/assets/c3d856c4-746d-4619-aa13-693be67d336b)

However clicking on the link works, as it opens the file contents in a new tab, so I know that my s3 configuration is valid.
I also use s3 for persistence.

Here is my labeling interface code:

```html
<View>
  <Labels name="label" toName="text">
    <Label value="PER" background="red"/>
  </Labels>

  <Text name="text" value="$text" valueType="url"/>
</View>
```

And my task.json

```json
{
    "data": {
      "text": "s3://textfiles/file.txt"
    }
}
```

I don't see any errors on the label-studio log. On the browser console I have this error:

```
Failed to load '[https://label.wip/tasks/55/presign/?fileuri=czM6Ly90ZXh0ZmlsZXMvZmlsZS50eHQ='](https://label.wip/tasks/55/presign/?fileuri=czM6Ly90ZXh0ZmlsZXMvZmlsZS50eHQ=%27). A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with 'TypeError: NetworkError when attempting to fetch resource.'.
```
On the network tab the request doesn't get a response, however I can see the error NS_ERROR_INTERCEPTION_FAILED.
I am using label studio and minio S3 in Kubernetes via heartex chart, so the S3 url I've supplied is the ingress hostname, since I understand that all queries to S3 are done by the client on the browser.

Label-Studio v1.13.1

Does anyone have any idea what I'm doing wrong?

**Comment by heidi-humansignal** [comment]
Hello DrissiReda,

Can you show us how you configured your S3 bucket in LS? It seems its more of issue on minio side

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11280807721)

**Comment by DrissiReda** [comment]
> Hello DrissiReda,
> 
> Can you show us how you configured your S3 bucket in LS? It seems its more of issue on minio side
> 
> Thank you, Abu
> 
> > Comment by Abubakar Saad
> > [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11280807721)

Hello, I use the helm chart's values:

```yaml
  persistence:
    enabled: true
    type: s3
    config:
      s3:
        accessKey: "minioadmin"
        secretKey: "minioadmin"
        region: "us-east-1"
        bucket: "labelstudio"
        folder: ""
        endpointUrl: "http://s3.wip" # external ingress of s3 api, accessible from the browser

```
