### ISSUE TITLE
403 Forbidden with CSRF verification failed after updating label-sutdio version [GKE] [helm chart]

### ISSUE THREAD

**Issue by ArmandXUuu** [heartexlabs/label-studio#6606]
**Describe the bug**
Our team has a LabelStudio deployment via helm chart on a Google (Cloud) Kubernetes Engine

*After trying to bump the docker image version from 1.13.1 to 1.14.0 users could no longer login with an error saying "Forbidden (403) CSRF verification failed" (see screenshot)*

**~To Reproduce~ About our implementation**
We used this chart:
```shell
helm repo add heartex https://charts.heartex.com/
helm repo update heartex
```
with custom values.yaml + image `heartexlabs/label-studio:1.14.0`

```yaml
...
global:
  image:
    repository: heartexlabs/label-studio
    pullPolicy: IfNotPresent
    # tag: "1.13.1"
    tag: "1.14.0"
...
  extraEnvironmentVars:
    EXPERIMENTAL_FEATURES: 1
    LABEL_STUDIO_HOST: "https://labelstudio.ourdomain.com"
    DJANGO_CSRF_TRUSTED_ORIGINS: "https://labelstudio.ourdomain.com" # yeah that's my desperate attempt
    SSRF_PROTECTION_ENABLED: "true"
```
Other values remain nearly the same as [here](https://github.com/HumanSignal/charts/blob/master/heartex/label-studio/values.yaml)

**Expected behavior**
A user should be able to login without any problem

**Screenshots**
![image (1)](https://github.com/user-attachments/assets/cce678c2-9192-4cfc-867d-0f5a73f27512)
![image](https://github.com/user-attachments/assets/8c143c4d-1947-4f02-ba8c-f92f9b873174)

**Environment:**
 - OS:
   - Client: MacOS 15.1, Safari / Ubuntu, Firefox
   - K8s: Google Kubernetes Engine 1.29.8-gke.1278000
 - Label Studio Version: 1.14.0

**Additional context**
I'd be happy to provide more information.

**Comment by CertainPassenger** [comment]
Same issue here. Label Studio deployed in our Kubernetes Cluster. After the upgrade from 1.13.2 to 1.14.0, using Edge or Firefox in Linux results in the CSRF validation failed error.

**Comment by jombooth** [comment]
Quick debugging step: does it work if you specify `CSRF_TRUSTED_ORIGINS` instead of `DJANGO_CSRF_TRUSTED_ORIGINS`?

**Comment by CertainPassenger** [comment]
I've already wanted to say that it also didn't work using `CSRF_TRUSTED_ORIGINS`, since we tried it already. But we've taken another look at the source code for parsing the `CSRF_TRUSTED_ORIGINS` in https://github.com/HumanSignal/label-studio/blob/develop/label_studio/core/settings/base.py#L700-L702 and seen that we've set the env variable wrong. Using the following snippet, it's now working for us:

```
env:
  - name: CSRF_TRUSTED_ORIGINS
    value: "https://example-a.com,https://example-b.com"
```

**Comment by farioas** [comment]
`LABEL_STUDIO_HOST` is no longer required, can you try with unset LABEL_STUDIO_HOST and CSRF_TRUSTED_ORIGINS env vars?

**Comment by ArmandXUuu** [comment]
> `LABEL_STUDIO_HOST` is no longer required, can you try with unset LABEL_STUDIO_HOST and CSRF_TRUSTED_ORIGINS env vars?

Thank you for your reply, I just tried with removing `LABEL_STUDIO_HOST` and `CSRF_TRUSTED_ORIGINS` but it still doesn't work.

**Comment by ArmandXUuu** [comment]
> Quick debugging step: does it work if you specify `CSRF_TRUSTED_ORIGINS` instead of `DJANGO_CSRF_TRUSTED_ORIGINS`?

In fact it works ! Thank you !
I've got:
``` yaml
global:
...
  extraEnvironmentVars:
    EXPERIMENTAL_FEATURES: 1
    CSRF_TRUSTED_ORIGINS: "https://labelstudio.ourdomain.com"
    SSRF_PROTECTION_ENABLED: "true"
...
```
