### ISSUE TITLE
Export project got no images

### ISSUE THREAD

**Issue by Timmy-Eink** [heartexlabs/label-studio#6651]
**Describe the bug**
I am using Docker Compose for Label Studio, and everything works fine. However, when I export the project, there are no images. For example, I exported in YOLO format and received the folders ‘images’ and ‘labels’, but the ‘images’ folder is empty while the ‘labels’ folder is normal contain labels txt.

I am using another Nginx as a reverse proxy.

Below is my docker-compose yml:

```
version: "3.9"
services:
  nginx:
    container_name: label-studio-nginx
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    # ports:
    #   - "8080:8085"
    #   - "8081:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=http://eih1aifsp01/label-studio
    #   Optional: Specify SSL termination certificate & key
    #   Just drop your cert.pem and cert.key into folder 'deploy/nginx/certs'
    #      - NGINX_SSL_CERT=/certs/cert.pem
    #      - NGINX_SSL_CERT_KEY=/certs/cert.key
    volumes:
      - /data/label-studio:/label-studio/data:rw # 將這裡的路徑改為 /data
      - ./deploy/nginx/certs:/certs:ro
    #   Optional: Override nginx default conf
    #      - ./deploy/my.conf:/etc/nginx/nginx.conf
    command: nginx
    networks:
      - my_network

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    # expose:
    #   - "8000"
    depends_on:
      - db
    environment:
      - LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - USER_UID=1002
      - USER_GID=1002
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=http://eih1aifsp01/label-studio
      - JSON_LOG=1
    volumes:
      - /data/label-studio/mydata:/label-studio/data:rw # 將這裡的路徑改為 /data
    command: label-studio-uwsgi
    networks:
      - my_network

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${POSTGRES_DATA_DIR:-/data/label-studio/postgres-data}:/var/lib/postgresql/data # 這裡可以根據需要調整
      - ./deploy/pgsql/certs:/var/lib/postgresql/certs:ro
    networks:
      - my_network

networks:
  my_network:
    external: true

```
my nginx :

```
version: "3.9"
services:
  nginx:
    container_name: main-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your Nginx config
    networks:
      - my_network

networks:
  my_network:
    external: true
```

config:
```
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        client_max_body_size 1000M;
        location /label-studio {
            proxy_pass http://label-studio-nginx:8085;  # Route to your app service
            proxy_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}

```

**Environment (please complete the following information):**
 - OS: ubuntu 22.04
 - Label Studio Version 1.4.0
