### ISSUE TITLE
I encountered a problem exporting YOLO using the label studio annotation tool Provide posture estimation training prompts ignoring corrupt image/label: labels require 7 columns each 

### ISSUE THREAD

**Issue by 1030907690** [heartexlabs/label-studio#6754]
**Describe the bug**
I encountered a problem exporting YOLO using the label studio annotation tool Provide posture estimation training prompts
```
ignoring corrupt image/label: labels require 7 columns each

ValueError: not enough values to unpack (expected 3, got 0)
```
I saw the official YOLO provided example coco8-pose (example address https://github.com/ultralytics/assets/releases/download/v0.0.0/coco8-pose.zip ）The label has 56 columns, so I think posture training should be related to the number of columns.

I found that the label txt generated by exporting YOLO using the label studio annotation tool always has 5 columns. How can I solve this problem?

**To Reproduce**
1. Export YOLO from Lab Studio
2. YAML configuration
```
path: D:/work/self/ultralytics/ultralytics/cfg/datasets/dinosaur_pose # dataset root dir
train: train/images # train images (relative to 'path') 4 images
val: train/images # val images (relative to 'path') 4 images
test: # test images (optional)

# Keypoints
kpt_shape: [1, 2] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
 
# Classes
names:
  0: hero
  1: nose
```
3.Training, abnormal after running
```
from ultralytics import YOLO
model = YOLO("yolo11n-pose.pt")  # load a pretrained model (recommended for training)
# Train the model
results = model.train(data="dinosaur-pose.yaml", epochs=100, imgsz=640)
```

![image](https://github.com/user-attachments/assets/84a75849-d8d8-473d-99df-282dc17afdac)

![image](https://github.com/user-attachments/assets/0e3fc237-09ec-4345-aff4-b0de116df00d)

**Expected behavior**
Do not warn or report errors.

**Screenshots**

![image](https://github.com/user-attachments/assets/84a75849-d8d8-473d-99df-282dc17afdac)

![image](https://github.com/user-attachments/assets/0e3fc237-09ec-4345-aff4-b0de116df00d)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version  1.14.0.post0

**Additional context**
Only one key point, key point nose, runtime prompt
