### ISSUE TITLE
External Database

### ISSUE THREAD

**Issue by harsh0522** [heartexlabs/label-studio#7181]
As written in instruction after adding external database pod is giving me error 

```
my values.yaml file 
global:
  pgConfig:
    host: "hostdetails"
    port: 5432
    dbName: "dbname"
    userName: "username"
    password:
      secretName: "labelstudio-db"
      secretKey: "POSTGRES_PASSWORD"
app:
  service:
    type: NodePort
    port: 8093

  extraEnvironmentVars:
    POSTGRES_SCHEMA: "labelstudio"

postgresql:
  enabled: false
```

![Image](https://github.com/user-attachments/assets/adb935b5-ad34-429c-8387-0f9871c5b69b)

what should i do ???? please help
