### ISSUE TITLE
What is the correct response format from ML Backend for Label Studio prediction retrieval?

### ISSUE THREAD

**Issue by arwinwijaya** [heartexlabs/label-studio#7630]
Hey all,

I'm struggling with the ML Backend response format for Label Studio when retrieving predictions. The error log says:

```
[ml.models::_get_predictions_from_ml_backend::300] [ERROR] ML backend returns an incorrect response, it must be a dict: [...]

```
But my current response looks like this (simplified):

```
[
  {
    "data": {
      "image": "/data/upload/3/714c19ea-28.1905dabf-tile_15_9.png"
    },
    "predictions": [
      {
        "model_version": "1.0.0",
        "score": 0.85,
        "results": [
          {
            "id": "some-uuid",
            "from_name": "label",
            "to_name": "image",
            "type": "RectangleLabels",
            "original_width": 640,
            "original_height": 640,
            "image_rotation": 0,
            "value": {
              "x": 93.76,
              "y": 157.78,
              "width": 108.04,
              "height": 76.01,
              "rotation": 0,
              "score": 0.96,
              "RectangleLabels": ["banana"]
            }
          }
          // more results here
        ]
      }
    ]
  }
]
```

The error specifically says:

`ML backend returns an incorrect response, it must be a dict
`

But my response is a list containing a dict.

So:

- What is the exact response format expected by Label Studio's ML Backend API for predictions?
- Should it be a dict instead of a list?
- Any example of a minimal valid response JSON?

I'm pretty sure my current response structure is off, but the docs are vague or confusing. Would really appreciate a clear example or pointer to the official spec.

Thanks!

**Comment by arwinwijaya** [comment]
![Image](https://github.com/user-attachments/assets/6d463f42-5b7c-43c1-93d8-d945fdca1a5e)

**Comment by heidi-humansignal** [comment]
Hello,

Thank you for contacting Label Studio,

Label Studio expects the `/predict` endpoint to return a **single dictionary per request**. and therefore the expected key is : "result" instead of "results"

Here's an example of the correct format:


    {"result": [{"from_name": "label","to_name": "image","type": "RectangleLabels","original_width": 640,"original_height": 640,"image_rotation": 0,"value": {"x": 93.76,"y": 157.78,"width": 108.04,"height": 76.01,"rotation": 0,"RectangleLabels": ["banana"]}}],"score": 0.85,"model_version": "1.0.0"}


Please let us know if it works out and if you need further support. Best Regards!

> Comment by Oussama Assili
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/15282297177)

**Comment by arwinwijaya** [comment]
Got it thanks @heidi-humansignal 

![Image](https://github.com/user-attachments/assets/7a2d696a-d1b7-4acd-a16e-b451fac6b798)

I have followed the response format you provided
{"result": [{"from_name": "label","to_name": "image","type": "RectangleLabels","original_width": 640,"original_height": 640,"image_rotation": 0,"value": {"x": 93.76,"y": 157.78,"width": 108.04,"height": 76.01,"rotation": 0,"RectangleLabels": ["banana"]}}],"score": 0.85,"model_version": "1.0.0"}

but why doesn't the **Prediction Score** appear?
should the score be two digits after the decimal point?

**Comment by instantgreen** [comment]
I'm experiencing this problem and have spent quite a few hours trying to fix it with the help of Gemini. 

Gemini did read this issue and additionally somebody else's report here: https://community.labelstud.io/t/problems-posting-model-results-via-the-predict-endpoint-from-a-flask-based-model-in-interactive-mode/457/2 

Since we weren't successful, I asked Gemini to craft a bug report with all the conclusions we came up to hopefully help the devs fix the problem.

---

Hello,

I can confirm that I am experiencing this exact issue on the `heartexlabs/label-studio:latest` Docker tag. I have spent a significant amount of time debugging this and can provide a complete, minimal reproducible example.

Despite sending a perfectly formatted JSON response (verified in the logs), the `label_studio_app` container consistently logs the misleading error: `ML backend returns an incorrect response, it must be a dict`.

**My Environment:**
*   **Label Studio Version:** `heartexlabs/label-studio:latest` (as of 2025-09-04)
*   **Deployment:** Docker Compose on a single server.
*   **ML Backend:** Custom Flask server using `waitress`, running in a separate Docker container on the same network.
*   **Labeling Configuration:** `<Image>` with `<RectangleLabels>`.

---

**To Reproduce the Issue:**

1.  **`docker-compose.yml`:**
    ```yaml
    services:
        db:
            container_name: label_studio_db
            hostname: db
            restart: unless-stopped
            environment:
            - TZ=Europe/Berlin
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            volumes:
            - ./label-studio/postgres-data:/var/lib/postgresql/data
            - ./label-studio/deploy/pgsql/certs:/var/lib/postgresql/certs:ro
            networks:
            - network

        app:
            image: heartexlabs/label-studio:latest
            container_name: label_studio_app
            restart: unless-stopped
            depends_on:
            - db
            - proxy
            environment:
            - TZ=Europe/Berlin
            - DJANGO_DB=default
            - POSTGRE_NAME=postgres
            - POSTGRE_USER=postgres
            - POSTGRE_PASSWORD=
            - POSTGRE_PORT=5432
            - POSTGRE_HOST=db
            - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
            - LABEL_STUDIO_LOG_LEVEL=DEBUG
            volumes:
            - ./label-studio/mydata:/label-studio/data:rw
            command: label-studio-uwsgi
            networks:
            - network

        nginx:
            image: heartexlabs/label-studio:latest
            container_name: label_studio_nginx
            restart: unless-stopped
            ports:
            - "8090:8085"
            depends_on:
            - app
            environment:
            - TZ=Europe/Berlin
            - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
            volumes:
            - ./label-studio/mydata:/label-studio/data:rw
            - ./label-studio/deploy/nginx/certs:/certs:ro
            command: nginx
            networks:
            - network

        nudenet_backend:
            build: ./label-studio/ml_backend
            container_name: nudenet_backend
            restart: unless-stopped
            ports:
            - "9090:9090"
            depends_on:
            - proxy
            volumes:
            - ./label-studio/mydata:/label-studio/data:ro
            deploy:
            resources:
                reservations:
                devices:
                    - driver: nvidia
                    count: 1
                    capabilities: [gpu]
            networks:
            - network
    ```

2.  **Labeling Interface XML:**
    ```xml
    <View>
        <Image name="image" value="$image" zoom="true"/>
        <RectangleLabels name="label" toName="image">
            <Label value="BUTTOCKS_EXPOSED" background="#FFC069"/>
            <Label value="FEMALE_BREAST_EXPOSED" background="#FFA39E"/>
            <Label value="FEMALE_GENITALIA_EXPOSED" background="#FF4D4F"/>
            <Label value="ANUS_EXPOSED" background="#FF7A45"/>
            <Label value="MALE_GENITALIA_EXPOSED" background="#597EF7"/>
            <Label value="FEET_EXPOSED" background="#D3F87A"/>
            <Label value="ARMPITS_EXPOSED" background="#B7EB8F"/>
            <Label value="BELLY_EXPOSED" background="#FFD591"/>
            <Label value="FEMALE_BREAST_COVERED" background="#ADC6FF"/>
            <Label value="FEMALE_GENITALIA_COVERED" background="#85A5FF"/>
            <Label value="MALE_BREAST_EXPOSED" background="#ADC6FF"/>
            <Label value="FACE_FEMALE" background="#E6F7FF"/>
            <Label value="FACE_MALE" background="#E6F7FF"/>
        </RectangleLabels>
    </View>
    ```

3.  **ML Backend `server.py`:**
    ```python
    from flask import Flask, request, jsonify
    from waitress import serve
    from model import NudeNetModel
    import json

    # Create Flask App
    app = Flask(__name__)

    # Load the model once during start
    print("Loading model, this might take a moment...")
    MODEL = NudeNetModel()
    print("Model loaded successfully.")

    # Label Studio calls this endpoint to check for availability
    @app.route('/health', methods=['GET'])
    def health():
        return jsonify({'status': 'UP'})

    # Label Studio calls this endpoint to get info about the model
    @app.route('/setup', methods=['POST'])
    def setup():
        return jsonify({'model_version': 'NudeNet Custom Server v1.0'})

    # Label Studio sends images for analysis
    @app.route('/predict', methods=['POST'])
    def predict():
        data = request.json
        tasks = data.get('tasks')
        if not tasks:
            # If there are no tasks, send back empty response
            return jsonify({"predictions": []})

        # model.py creats list of predictions
        predictions = MODEL.predict(tasks)

        return jsonify({"predictions": predictions})
        
    # Start server
    if __name__ == '__main__':
        print("Starting Waitress server on http://[::]:9090")
        serve(app, host='::', port=9090)

    ```

4.  **ML Backend `model.py`:**
    ```python
    from nudenet import NudeDetector
    from PIL import Image
    import os

    class NudeNetModel:
        def __init__(self, **kwargs):
            self.from_name = 'label'
            self.to_name = 'image'
            print("Initializing NudeNet detector...")
            self.detector = NudeDetector()
            print("NudeNet detector initialized.")

        def predict(self, tasks):
            predictions = []
            for task in tasks:
                image_url_relative = task['data']['image']

                if image_url_relative.startswith('/data/'):
                    path_after_data = image_url_relative.split('/data/', 1)[1]
                    image_path_in_container = os.path.join("/label-studio/data/media", path_after_data)
                else:
                    image_path_in_container = image_url_relative
                    print(f"Warning: Unexpected image path format. Using as is: {image_path_in_container}")

                print(f"Processing image: {image_path_in_container}")
                try:
                    pil_image = Image.open(image_path_in_container)
                    original_width, original_height = pil_image.size
                    results = self.detector.detect(image_path_in_container)
                except Exception as e:
                    print(f"Error processing image {image_path_in_container}: {e}")
                    continue

                prediction_items = []
                for result in results:
                    box = result['box']
                    label = result['class']
                    score = result['score']

                    x_abs, y_abs, width_abs, height_abs = box

                    single_box_annotation = {
                        "from_name": self.from_name,
                        "to_name": self.to_name,
                        "type": "rectanglelabels",
                        "score": float(score),
                        "value": {
                            "x": float((x_abs / original_width) * 100),
                            "y": float((y_abs / original_height) * 100),
                            "width": float((width_abs / original_width) * 100),
                            "height": float((height_abs / original_height) * 100),
                            "rectanglelabels": [label]
                        }
                    }
                    prediction_items.append(single_box_annotation)

                # Add the dictionary that only contains the "result" key.
                predictions.append({
                    "result": prediction_items
                })

            return predictions
    ```

5.  **Steps:**
    1.  Run `docker compose up -d`.
    2.  Create a new project in Label Studio and use the XML above for the labeling interface.
    3.  Connect the ML backend in the project settings (e.g., at `http://nudenet_backend:9090`).
    4.  Upload any image.
    5.  Observe the logs of the `label_studio_app` container.

---

**Expected Behavior:**
The bounding box predictions should appear in the labeling UI.

**Actual Behavior:**
The UI shows no predictions. The `label_studio_app` log shows the following error, even though the JSON it displays is perfectly formatted according to the documentation:

```
[ERROR] ML backend returns an incorrect response, it must be a dict: {'predictions': [{'result': [{'from_name': 'label', 'score': 0.8555..., 'to_name': 'image', 'type': 'rectanglelabels', 'value': {'height': 12.12..., 'rectanglelabels': ['FACE_FEMALE'], ...}}]}]}
```

**What I've Systematically Ruled Out:**
The error is not caused by the format of the JSON. I have tested every possible permutation:
1.  **Response Wrapper:** Both `jsonify({"predictions": predictions})` and `jsonify(predictions)` produce the same error.
2.  **Internal Structure:** The `model.py` now produces the exact structure from the official documentation, with each bounding box as a separate item in the `result` list.
3.  **Data Types:** All coordinates and scores are correctly cast to standard Python `float`.
4.  **Configuration Match:** `from_name` ('label') and `to_name` ('image') perfectly match the labeling config.
5.  **Value Keys:** The critical key within the `value` object has been tested with `label`, `labels`, and the correct `rectanglelabels`—all fail.
6.  **Optional Fields:** Removing the optional top-level `score` per task does not solve the issue.

Given this exhaustive testing, I strongly suspect this is a regression or a bug in the current `:latest` version of Label Studio's ML backend parser.
