### ISSUE TITLE
[Feature Request] Support for Chained/Sequential Pre-labeling Models

### ISSUE THREAD

**Issue by chang-wd** [heartexlabs/label-studio#7724]
For example, in document analysis workflows:

Model 1 (OCR): Extract text from images → outputs text regions with bounding boxes
Model 2 (Text Classification): Classify extracted text → outputs text categories (title, content, contact info, etc.)
Model 3 (NER/Sentiment): Further process classified text → outputs entities or sentiment labels
Currently, we have to either:

Combine all models into a single ML backend (complex and hard to maintain)
Run models separately and manually combine results (inefficient)
Use external preprocessing (loses the benefits of Label Studio's pre-labeling workflow)

**Describe the solution you'd like**
Native Pipeline Support
Add native support for model chaining in Label Studio with configuration like:
```yaml
ml_backends:
  - name: "ocr_model"
    url: "http://localhost:9090"
    output_to: ["text_classification_model"]
  
  - name: "text_classification_model" 
    url: "http://localhost:9091"
    input_from: ["ocr_model"]
    output_to: ["sentiment_model"]
    
  - name: "sentiment_model"
    url: "http://localhost:9092" 
    input_from: ["text_classification_model"]
```

**Describe alternatives you've considered**

**Additional context**
